name: Push DockerHub Image to AWS ECR

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Change branch if needed

jobs:
  push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Step to pull, tag, and push first Docker image
      - name: Pull DockerHub Image 1
        run: |
          docker pull ${{ secrets.DOCKERHUB_IMAGE_1 }}

      - name: Tag Image 1 for ECR
        run: |
          IMAGE_NAME_1=$(echo "${{ secrets.DOCKERHUB_IMAGE_1 }}" | cut -d':' -f1 | cut -d'/' -f2)
          docker tag ${{ secrets.DOCKERHUB_IMAGE_1 }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_NAME_1-latest

      - name: Push Image 1 to ECR
        run: |
          IMAGE_NAME_1=$(echo "${{ secrets.DOCKERHUB_IMAGE_1 }}" | cut -d':' -f1 | cut -d'/' -f2)
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_NAME_1-latest

      # Step to pull, tag, and push second Docker image
      - name: Pull DockerHub Image 2
        run: |
          docker pull ${{ secrets.DOCKERHUB_IMAGE_2 }}

      - name: Tag Image 2 for ECR
        run: |
          IMAGE_NAME_2=$(echo "${{ secrets.DOCKERHUB_IMAGE_2 }}" | cut -d':' -f1 | cut -d'/' -f2)
          docker tag ${{ secrets.DOCKERHUB_IMAGE_2 }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_NAME_2-latest

      - name: Push Image 2 to ECR
        run: |
          IMAGE_NAME_2=$(echo "${{ secrets.DOCKERHUB_IMAGE_2 }}" | cut -d':' -f1 | cut -d'/' -f2)
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_NAME_2-latest

  notify:
    needs: push_to_ecr
    runs-on: ubuntu-latest
    steps:
      - name: Send Email using Gmail SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "GitHub Actions: Docker Images Pushed to AWS ECR"
          body: "The Docker images have been successfully pushed to AWS ECR."
          to: "saikarthik261@gmail.com,praneethssr.2002@mail.com,nagelijaisai@gmail.com"
          from: ${{ secrets.GMAIL_USERNAME }}
